### ISSUE TITLE
can't open datatable

### ISSUE THREAD

**Issue by DaaaaaSan** [keitannunes/KeifunsDatatableEditor#16]
![image](https://github.com/user-attachments/assets/071311a5-aec9-4aa4-acf1-4eccdd65fcd0)

**Comment by DaaaaaSan** [comment]
![image](https://github.com/user-attachments/assets/8ce32252-8ec4-4d7c-a75e-3394e854ce63)

**Comment by keitannunes** [comment]
@DaaaaaSan You're supposed to fill those fields with the corresponding encryption keys. DM me on discord if you need them
